import { createReadStream, promises as fsp } from 'node:fs';
import path from 'node:path';
import { randomBytes } from 'node:crypto';

// Local-disk driver: the development default, and fine on a host whose disk
// survives a redeploy (the VPS). Not on Render, whose container disk is wiped
// on every deploy — see storage/index.js#ephemeralDiskWarning.
//
// Objects live at <root>/<key>. Content type is not stored: every caller keeps
// it next to the key in the database, which is where it is served from.

function invalidKey(key) {
  const e = new Error(`Invalid storage key: ${JSON.stringify(key)}`);
  e.status = 400;
  return e;
}

export function createDiskDriver({ root }) {
  const base = path.resolve(root);

  // Keys are generated by the app, but a key is still a path: it is resolved
  // under the root and refused if it would leave it.
  const pathFor = (key) => {
    const k = String(key || '');
    if (!k || k.includes('\0') || k.startsWith('/') || k.startsWith('\\')
      || k.split(/[\\/]/).some((seg) => seg === '..' || seg === '')) {
      throw invalidKey(key);
    }
    const full = path.resolve(base, k);
    if (!full.startsWith(base + path.sep)) throw invalidKey(key);
    return full;
  };

  async function put(key, body, { contentType = null } = {}) {
    const full = pathFor(key);
    const data = Buffer.isBuffer(body) ? body : Buffer.from(body);
    await fsp.mkdir(path.dirname(full), { recursive: true });
    // Written beside the target and renamed into place, so a reader never sees
    // a half-written file and a crash leaves no truncated object.
    const tmp = `${full}.${randomBytes(6).toString('hex')}.tmp`;
    await fsp.writeFile(tmp, data);
    await fsp.rename(tmp, full);
    return { key, size: data.length, contentType };
  }

  async function head(key) {
    try {
      const stat = await fsp.stat(pathFor(key));
      return stat.isFile() ? { size: stat.size, contentType: null } : null;
    } catch (err) {
      if (err.code === 'ENOENT') return null;
      throw err;
    }
  }

  async function get(key) {
    const meta = await head(key);
    if (!meta) return null;
    return { stream: createReadStream(pathFor(key)), size: meta.size, contentType: null };
  }

  async function getBuffer(key) {
    try {
      return await fsp.readFile(pathFor(key));
    } catch (err) {
      if (err.code === 'ENOENT') return null;
      throw err;
    }
  }

  async function remove(key) {
    try {
      await fsp.unlink(pathFor(key));
    } catch (err) {
      if (err.code !== 'ENOENT') throw err;
    }
  }

  // Every stored key, for the migration script. Temp files from an interrupted
  // write are skipped.
  async function* list(prefix = '') {
    async function* walk(dir) {
      let entries;
      try {
        entries = await fsp.readdir(dir, { withFileTypes: true });
      } catch (err) {
        if (err.code === 'ENOENT') return;
        throw err;
      }
      for (const entry of entries) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) yield* walk(full);
        else if (entry.isFile() && !entry.name.endsWith('.tmp')) {
          const key = path.relative(base, full).split(path.sep).join('/');
          if (key.startsWith(prefix)) yield key;
        }
      }
    }
    yield* walk(base);
  }

  return {
    driver: 'disk',
    // Whether objects survive a redeploy is a property of the host, not of
    // this code; callers that must not lose bytes check `objectStore` instead.
    objectStore: false,
    root: base,
    put,
    head,
    get,
    getBuffer,
    delete: remove,
    list,
    // No URL can be handed out for a file on this disk; callers stream it.
    signedUrl: async () => null,
    describe: () => `local disk at ${base}`,
  };
}
