import test from 'node:test';
import assert from 'node:assert/strict';
import { prisma } from '../lib/prisma.js';
import {
  DEFAULT_CUSTOMIZATIONS,
  SECTION_KEYS,
  getAllCustomizations,
  getSection,
  updateSection,
  resetSection,
  checkSafeDeletion,
  autoGenerateDealTaskOnStageChange,
} from './crmCustomization.service.js';

let dbAvailable = false;
let workspaceId;
let contactId;
let dealId;

test.before(async () => {
  try {
    await prisma.$connect();
    dbAvailable = true;
  } catch {
    return;
  }

  const stamp = Date.now();
  const ws = await prisma.workspace.create({
    data: { name: `test-customization-${stamp}` },
  });
  workspaceId = ws.id;

  const contact = await prisma.contact.create({
    data: {
      workspaceId,
      name: 'Customization Test Contact',
      phoneNumber: `+9198${stamp.toString().slice(-8)}`,
    },
  });
  contactId = contact.id;

  const deal = await prisma.deal.create({
    data: {
      workspaceId,
      contactId,
      title: 'Enterprise Cloud Deal',
      value: 50000,
      stage: 'QUALIFICATION',
    },
  });
  dealId = deal.id;
});

test.after(async () => {
  if (!dbAvailable || !workspaceId) return;
  await prisma.savedView.deleteMany({ where: { workspaceId } }).catch(() => {});
  await prisma.task.deleteMany({ where: { workspaceId } }).catch(() => {});
  await prisma.deal.deleteMany({ where: { workspaceId } }).catch(() => {});
  await prisma.lead.deleteMany({ where: { workspaceId } }).catch(() => {});
  await prisma.contact.deleteMany({ where: { workspaceId } }).catch(() => {});
  await prisma.pipelineStage.deleteMany({ where: { workspaceId } }).catch(() => {});
  await prisma.workspace.delete({ where: { id: workspaceId } }).catch(() => {});
});

test('SECTION_KEYS defines all 10 customization sections', () => {
  assert.equal(SECTION_KEYS.length, 10);
  assert.ok(SECTION_KEYS.includes('lead_lifecycle'));
  assert.ok(SECTION_KEYS.includes('prospecting_criteria'));
  assert.ok(SECTION_KEYS.includes('deal_mode'));
  assert.ok(SECTION_KEYS.includes('lead_tags'));
  assert.ok(SECTION_KEYS.includes('lead_sources'));
  assert.ok(SECTION_KEYS.includes('call_outcomes'));
  assert.ok(SECTION_KEYS.includes('visit_outcomes'));
  assert.ok(SECTION_KEYS.includes('deal_setup'));
  assert.ok(SECTION_KEYS.includes('ticket_customization'));
  assert.ok(SECTION_KEYS.includes('document_categories'));
});

test('getAllCustomizations returns defaults for a fresh workspace', async (t) => {
  if (!dbAvailable) return t.skip('database not reachable');
  const all = await getAllCustomizations(workspaceId);
  for (const key of SECTION_KEYS) {
    assert.ok(all[key], `Missing customization key: ${key}`);
  }
  assert.equal(all.deal_mode.mode, 'FLEXIBLE');
  assert.ok(all.call_outcomes.outcomes.length > 0);
  assert.ok(all.lead_tags.tags.length > 0);
});

test('getSection and updateSection work for lead_tags', async (t) => {
  if (!dbAvailable) return t.skip('database not reachable');
  const current = await getSection(workspaceId, 'lead_tags');
  assert.ok(Array.isArray(current.tags));

  const updatedTags = [
    ...current.tags,
    { id: 'custom_tag_1', name: 'VIP Buyer', color: '#ff00ff', category: 'Priority' },
  ];

  await updateSection(workspaceId, 'lead_tags', { tags: updatedTags });
  const reloaded = await getSection(workspaceId, 'lead_tags');
  assert.equal(reloaded.tags.length, current.tags.length + 1);
  assert.ok(reloaded.tags.some((t) => t.name === 'VIP Buyer'));
});

test('resetSection restores default configuration', async (t) => {
  if (!dbAvailable) return t.skip('database not reachable');
  await resetSection(workspaceId, 'lead_tags');
  const reset = await getSection(workspaceId, 'lead_tags');
  assert.equal(reset.tags.length, DEFAULT_CUSTOMIZATIONS.lead_tags.tags.length);
  assert.ok(!reset.tags.some((t) => t.name === 'VIP Buyer'));
});

test('deal_mode update and automatic task creation', async (t) => {
  if (!dbAvailable) return t.skip('database not reachable');
  // Configure deal mode to AUTOMATIC
  await updateSection(workspaceId, 'deal_mode', {
    mode: 'AUTOMATIC',
    autoTaskConfig: {
      followUpDueDays: 3,
      defaultPriority: 'HIGH',
      stageTaskTemplates: {
        PROPOSAL: 'Deliver commercial proposal to client',
      },
    },
  });

  const deal = await prisma.deal.findUnique({ where: { id: dealId } });
  const task = await autoGenerateDealTaskOnStageChange(workspaceId, deal, 'PROPOSAL');
  assert.ok(task, 'Task should have been auto-generated');
  assert.equal(task.title, 'Deliver commercial proposal to client');
  assert.equal(task.dealId, dealId);
  assert.equal(task.status, 'PENDING');
});

test('checkSafeDeletion prevents deleting active deal stages', async (t) => {
  if (!dbAvailable) return t.skip('database not reachable');
  const check = await checkSafeDeletion(workspaceId, 'deal_setup', 'QUALIFICATION');
  assert.equal(check.safe, false);
  assert.ok(check.reason.includes('deal(s) are currently in this stage'));

  const checkSafe = await checkSafeDeletion(workspaceId, 'deal_setup', 'NEEDS_ANALYSIS');
  assert.equal(checkSafe.safe, true);
});
