import { prisma } from '../lib/prisma.js';
import { computeWorkspaceDealHealth, computeDealHealth } from './dealHealth.service.js';
import { validateCrmCustomFields } from './customFields.service.js';
import { scopeFilter, withScope } from './recordScope.service.js';
import { assertRecordReferences } from './crmReferences.js';
import { emitCrmEvent } from './workflowCrm.service.js';
import { awardXp, unlockAchievement, revokeXp, earnsWonDeal, checkWinAchievements } from './gamification.service.js';
import { autoGenerateDealTaskOnStageChange } from './crmCustomization.service.js';
import { assertKnownStage } from './pipelineStages.service.js';

const CLOSED_STAGES = ['CLOSED_WON', 'CLOSED_LOST'];

const PRISMA_DEAL_STAGES = new Set(['QUALIFICATION', 'NEEDS_ANALYSIS', 'PROPOSAL', 'NEGOTIATION', 'CLOSED_WON', 'CLOSED_LOST']);

// Generous budget for multi-step interactive transactions over pooled/remote DB connections
const TX_OPTS = { maxWait: 15_000, timeout: 30_000 };

const DEAL_INCLUDE = {
  contact: { select: { id: true, name: true, phoneNumber: true, email: true } },
  owner: { select: { id: true, name: true, email: true } },
  lead: { select: { id: true, status: true, score: true } },
};

// The board used to load every deal in the workspace in one query. Capped by
// default; `total` still counts everything, so a client can tell it got a page.
const LIST_DEFAULT_LIMIT = 500;
const LIST_MAX_LIMIT = 1000;

export async function listDeals(workspaceId, { stage = '', ownerUserId = '', limit, offset } = {}, user = null) {
  const take = Math.min(Math.max(Number.parseInt(limit, 10) || LIST_DEFAULT_LIMIT, 1), LIST_MAX_LIMIT);
  const skip = Math.max(Number.parseInt(offset, 10) || 0, 0);
  const scope = user ? await scopeFilter(workspaceId, user) : {};
  const filters = {
    workspaceId,
    ...(ownerUserId ? { ownerUserId } : {}),
  };

  // A deal's effective stage is customFields.stageKey when set, else the enum.
  // The candidates are narrowed in SQL and the exact match is made below:
  // a deal on a built-in stage may still carry other custom-field values, and
  // "stageKey absent" is not something a JSON filter expresses reliably.
  if (stage) {
    filters.AND = [
      PRISMA_DEAL_STAGES.has(stage)
        ? { OR: [{ stage }, { customFields: { path: ['stageKey'], equals: stage } }] }
        : { customFields: { path: ['stageKey'], equals: stage } },
    ];
  }
  // AND, not spread: the stage filter's `OR` would otherwise replace the scope.
  const where = withScope(filters, scope);

  // Health is computed for the page being returned, in one fixed set of
  // queries rather than per card — not for every open deal in the workspace,
  // which it used to be on every board load (CF-048).
  const [rows, count] = await Promise.all([
    prisma.deal.findMany({ where, include: DEAL_INCLUDE, orderBy: [{ updatedAt: 'desc' }, { id: 'desc' }], skip, take }),
    prisma.deal.count({ where }),
  ]);
  const health = await computeWorkspaceDealHealth(workspaceId, { dealIds: rows.map((deal) => deal.id) });
  const data = stage ? rows.filter((deal) => (deal.customFields?.stageKey || deal.stage) === stage) : rows;
  return {
    data: data.map((deal) => {
      const effectiveStage = deal.customFields?.stageKey || deal.stage;
      return { ...deal, stage: effectiveStage, health: health.get(deal.id) ?? null };
    }),
    total: stage ? data.length : count,
    limit: take,
    offset: skip,
  };
}

export async function getDeal(workspaceId, id, user = null) {
  const scope = user ? await scopeFilter(workspaceId, user) : {};
  const deal = await prisma.deal.findFirst({
    where: { id, workspaceId, ...scope },
    include: {
      ...DEAL_INCLUDE,
      stageHistory: {
        orderBy: { changedAt: 'asc' },
        include: { changedByUser: { select: { id: true, name: true } } },
      },
    },
  });
  if (!deal) { const e = new Error('Deal not found'); e.status = 404; throw e; }
  const effectiveStage = deal.customFields?.stageKey || deal.stage;
  const mappedStageHistory = (deal.stageHistory || []).map((h) => ({
    ...h,
    fromStage: h.fromStageKey || h.fromStage,
    toStage: h.toStageKey || h.toStage,
  }));
  return { ...deal, stage: effectiveStage, stageHistory: mappedStageHistory, health: await computeDealHealth(workspaceId, id) };
}

export async function createDeal(workspaceId, body, userId) {
  const contact = await prisma.contact.findFirst({ where: { id: body.contactId, workspaceId }, select: { id: true } });
  if (!contact) { const e = new Error('Contact not found'); e.status = 404; throw e; }

  if (body.leadId) {
    const lead = await prisma.lead.findFirst({ where: { id: body.leadId, workspaceId }, select: { id: true } });
    if (!lead) { const e = new Error('Lead not found'); e.status = 404; throw e; }
  }
  await assertRecordReferences(workspaceId, { ownerUserId: body.ownerUserId });

  const requestedStage = body.stage || 'QUALIFICATION';
  await assertKnownStage(workspaceId, requestedStage);
  const isPrismaStage = PRISMA_DEAL_STAGES.has(requestedStage);
  const dbStage = isPrismaStage ? requestedStage : 'QUALIFICATION';
  const customFields = isPrismaStage
    ? (body.customFields || null)
    : { ...(body.customFields || {}), stageKey: requestedStage };

  return prisma.$transaction(async (tx) => {
    const deal = await tx.deal.create({
      data: {
        workspaceId,
        contactId: body.contactId,
        leadId: body.leadId ?? null,
        title: body.title,
        value: body.value ?? null,
        currency: body.currency || 'INR',
        stage: dbStage,
        customFields,
        ownerUserId: body.ownerUserId ?? null,
        expectedCloseDate: body.expectedCloseDate ?? null,
        closedAt: CLOSED_STAGES.includes(requestedStage) ? new Date() : null,
      },
      include: DEAL_INCLUDE,
    });
    const toStageDb = PRISMA_DEAL_STAGES.has(requestedStage) ? requestedStage : 'QUALIFICATION';
    await tx.dealStageHistory.create({
      data: {
        workspaceId,
        dealId: deal.id,
        fromStage: null,
        toStage: toStageDb,
        fromStageKey: null,
        toStageKey: requestedStage,
        changedByUserId: userId ?? null,
      },
    });
    return { ...deal, stage: requestedStage };
  }, TX_OPTS).then((deal) => {
    const owner = deal.ownerUserId || userId;
    if (owner) {
      unlockAchievement(workspaceId, owner, 'first_deal')
        .catch((e) => console.error('[Gamification] achievement failed:', e.message));
    }
    return deal;
  });
}

// Stage is deliberately not updatable here — it moves only through
// updateDealStage(), which is what guarantees every move lands in the history.
export async function updateDeal(workspaceId, id, updates, user = null) {
  const scope = user ? await scopeFilter(workspaceId, user) : {};
  const deal = await prisma.deal.findFirst({ where: { id, workspaceId, ...scope }, select: { id: true, customFields: true } });
  if (!deal) { const e = new Error('Deal not found'); e.status = 404; throw e; }
  await assertRecordReferences(workspaceId, { ownerUserId: updates.ownerUserId, contactId: updates.contactId });

  const data = { ...updates };
  // An itemised deal's value is the sum of its lines (dealLineItems.service.js);
  // a hand-typed figure would contradict them.
  if (data.value !== undefined && await prisma.dealLineItem.count({ where: { workspaceId, dealId: id } }) > 0) {
    delete data.value;
  }
  const customFields = await validateCrmCustomFields(workspaceId, 'deal', updates.customFields, deal.customFields);
  if (customFields === undefined) delete data.customFields;
  else data.customFields = customFields;

  return prisma.deal.update({ where: { id }, data, include: DEAL_INCLUDE });
}

export async function deleteDeal(workspaceId, id, user = null) {
  const scope = user ? await scopeFilter(workspaceId, user) : {};
  const deal = await prisma.deal.findFirst({ where: { id, workspaceId, ...scope }, select: { id: true } });
  if (!deal) { const e = new Error('Deal not found'); e.status = 404; throw e; }
  await prisma.deal.delete({ where: { id } });
  revokeXp(workspaceId, 'won_deal', id).catch((e) => console.error('[Gamification] revoke failed:', e.message));
}

// One row of stage history per move, written in the same transaction as the
// move itself — the pipeline board's drag/drop is only auditable if a stage
// change can never be recorded without its history entry.
export async function updateDealStage(workspaceId, id, stageOrObj, userId, user = null) {
  const stage = typeof stageOrObj === 'string' ? stageOrObj : stageOrObj?.stage;
  const lostReason = typeof stageOrObj === 'object' ? stageOrObj?.lostReason : null;

  // Scope is resolved before the transaction: a member must not be able to
  // move a deal they cannot see.
  const scope = user ? await scopeFilter(workspaceId, user) : {};
  await assertKnownStage(workspaceId, stage);

  const isPrismaStage = PRISMA_DEAL_STAGES.has(stage);
  const dbStage = isPrismaStage ? stage : 'QUALIFICATION';

  const updated = await prisma.$transaction(async (tx) => {
    const deal = await tx.deal.findFirst({ where: { id, workspaceId, ...scope } });
    if (!deal) { const e = new Error('Deal not found'); e.status = 404; throw e; }

    const previousEffectiveStage = deal.customFields?.stageKey || deal.stage;

    const customFields = typeof deal.customFields === 'object' && deal.customFields !== null
      ? { ...deal.customFields }
      : {};
    if (isPrismaStage) {
      delete customFields.stageKey;
    } else {
      customFields.stageKey = stage;
    }

    const updated = await tx.deal.update({
      where: { id },
      data: {
        stage: dbStage,
        customFields: Object.keys(customFields).length > 0 ? customFields : null,
        closedAt: CLOSED_STAGES.includes(stage) ? (deal.closedAt ?? new Date()) : null,
        lostReason: stage === 'CLOSED_LOST' ? (lostReason ?? deal.lostReason ?? null) : null,
      },
      include: DEAL_INCLUDE,
    });

    const fromStageDb = PRISMA_DEAL_STAGES.has(previousEffectiveStage) ? previousEffectiveStage : 'QUALIFICATION';
    const toStageDb = PRISMA_DEAL_STAGES.has(stage) ? stage : 'QUALIFICATION';

    await tx.dealStageHistory.create({
      data: {
        workspaceId,
        dealId: id,
        fromStage: fromStageDb,
        toStage: toStageDb,
        fromStageKey: previousEffectiveStage,
        toStageKey: stage,
        changedByUserId: userId ?? null,
      },
    });

    return { ...updated, stage, previousStage: previousEffectiveStage };
  }, TX_OPTS);

  // Rewarded on the outcome, not the activity: only entering CLOSED_WON pays,
  // only for a deal with a value that existed before today, and the dedupe key
  // means re-closing the same deal cannot farm points. Leaving CLOSED_WON
  // takes the award back.
  if (stage === 'CLOSED_WON' && updated.previousStage !== 'CLOSED_WON' && updated.ownerUserId && earnsWonDeal(updated)) {
    awardXp(workspaceId, updated.ownerUserId, 'won_deal', { recordType: 'deal', recordId: id })
      .then(() => checkWinAchievements(workspaceId, updated.ownerUserId))
      .catch((e) => console.error('[Gamification] award failed:', e.message));
  } else if (updated.previousStage === 'CLOSED_WON' && stage !== 'CLOSED_WON') {
    revokeXp(workspaceId, 'won_deal', id).catch((e) => console.error('[Gamification] revoke failed:', e.message));
  }

  // Emitted after the transaction commits, so a workflow can never observe a
  // stage change that later rolled back.
  if (updated.previousStage !== stage) {
    emitCrmEvent(workspaceId, 'deal_stage_changed', {
      dealId: id,
      leadId: updated.leadId ?? null,
      contactId: updated.contactId,
      stage,
      previousStage: updated.previousStage,
    });

    // Automatic Deal Mode: auto-create structured follow-up task if configured
    try {
      await autoGenerateDealTaskOnStageChange(workspaceId, updated, stage, userId);
    } catch (e) {
      console.error('[DealMode] auto-generate task error:', e.message);
    }
  }

  return updated;
}
