import { prisma } from '../lib/prisma.js';
import { scoreDealHealth, buildSignals as buildHealthSignals } from './dealHealth.service.js';
import { scopeFilter } from './recordScope.service.js';

// Next-best-action.
//
// §52 requires every recommendation to state what to do, why, and the evidence
// behind it. Nothing here is generated by a model: each rule reads facts that
// already exist in the database and cites them. A recommendation a rep cannot
// verify is one they will learn to ignore.
//
// Deliberately *not* predictive. These are observations with an obvious next
// step, not forecasts of what will happen.

const DAY = 86400000;
const daysSince = (d, now) => (d ? Math.floor((now - new Date(d).getTime()) / DAY) : null);

// Higher sorts first. Chosen so a breached commitment outranks a suggestion:
// an overdue task is something already promised, a stale deal is merely drifting.
const URGENCY = {
  OVERDUE_TASK: 100,
  CLOSE_DATE_PASSED: 90,
  HOT_LEAD_UNTOUCHED: 80,
  DEAL_NO_ACTIVITY: 70,
  DEAL_STALLED: 60,
  TICKET_BREACHING: 95,
  DEAL_NO_NEXT_STEP: 40,
  DEAL_MISSING_AMOUNT: 30,
  LEAD_UNASSIGNED: 35,
};

const rec = ({ key, urgency, title, why, evidence, record, action }) => ({
  key, urgency, title, why, evidence, record, action,
});

/**
 * Ranked recommendations for one workspace, scoped to what the caller may see.
 *
 * Everything is derived in a fixed number of queries: a per-record query would
 * make this the slowest screen in the product precisely when there is most to
 * act on.
 */
export async function getRecommendations(workspaceId, user = null, { limit = 20, now = new Date() } = {}) {
  const scope = user ? await scopeFilter(workspaceId, user) : {};
  const taskScope = user ? await scopeFilter(workspaceId, user, { ownerField: 'assignedToUserId' }) : {};

  const [overdueTasks, openDeals, leads, breachingTickets] = await Promise.all([
    prisma.task.findMany({
      where: { workspaceId, ...taskScope, status: 'PENDING', dueDate: { lt: now } },
      include: {
        deal: { select: { id: true, title: true } },
        lead: { select: { id: true, contact: { select: { name: true } } } },
        contact: { select: { id: true, name: true } },
      },
      orderBy: { dueDate: 'asc' },
      take: 50,
    }),
    prisma.deal.findMany({
      where: { workspaceId, ...scope, stage: { notIn: ['CLOSED_WON', 'CLOSED_LOST'] } },
      select: {
        id: true, title: true, stage: true, value: true, ownerUserId: true,
        expectedCloseDate: true, createdAt: true,
        contact: { select: { id: true, name: true } },
        stageHistory: { orderBy: { changedAt: 'asc' }, select: { changedAt: true } },
      },
      take: 200,
    }),
    prisma.lead.findMany({
      where: { workspaceId, ...scope, status: { in: ['NEW', 'CONTACTED', 'QUALIFIED'] } },
      select: {
        id: true, score: true, status: true, ownerUserId: true, createdAt: true,
        contact: { select: { id: true, name: true } },
      },
      orderBy: { score: 'desc' },
      take: 100,
    }),
    prisma.crmTicket.findMany({
      where: {
        workspaceId, ...scope,
        status: { notIn: ['RESOLVED', 'CLOSED'] },
        dueAt: { lt: new Date(now.getTime() + 2 * 3600_000) }, // breached or within 2h
      },
      select: { id: true, ticketNumber: true, subject: true, dueAt: true, priority: true },
      orderBy: { dueAt: 'asc' },
      take: 30,
    }),
  ]);

  const dealIds = openDeals.map((d) => d.id);
  const [activityByDeal, openTasksByDeal] = await Promise.all([
    dealIds.length
      ? prisma.crmActivity.groupBy({ by: ['dealId'], where: { workspaceId, dealId: { in: dealIds } }, _max: { createdAt: true } })
      : [],
    dealIds.length
      ? prisma.task.groupBy({ by: ['dealId'], where: { workspaceId, dealId: { in: dealIds }, status: 'PENDING' }, _count: { _all: true } })
      : [],
  ]);
  const lastActivity = new Map(activityByDeal.map((g) => [g.dealId, g._max.createdAt]));
  const openTasks = new Map(openTasksByDeal.map((g) => [g.dealId, g._count._all]));

  const out = [];

  // ── Overdue tasks ────────────────────────────────────────────────────────
  for (const task of overdueTasks) {
    const late = daysSince(task.dueDate, now);
    const subject = task.deal?.title || task.lead?.contact?.name || task.contact?.name || null;
    out.push(rec({
      key: `task:${task.id}`,
      urgency: URGENCY.OVERDUE_TASK + Math.min(late, 20),
      title: `Complete "${task.title}"`,
      why: 'This was committed to and the date has passed.',
      evidence: [
        // "Due 0 days ago" is how a date reads when nobody checked the copy.
        late === 0 ? 'Due today' : `Due ${late} day${late === 1 ? '' : 's'} ago`,
        ...(subject ? [`Related to ${subject}`] : []),
      ],
      record: { type: 'task', id: task.id, label: task.title },
      action: { type: 'open_task', label: 'Open task' },
    }));
  }

  // ── Tickets about to breach ──────────────────────────────────────────────
  for (const ticket of breachingTickets) {
    const overdue = ticket.dueAt < now;
    const hours = Math.abs(Math.round((ticket.dueAt - now) / 3600_000));
    out.push(rec({
      key: `ticket:${ticket.id}`,
      urgency: URGENCY.TICKET_BREACHING + (overdue ? 10 : 0),
      title: `Respond to ${ticket.ticketNumber}: ${ticket.subject}`,
      why: overdue ? 'The response target has been missed.' : 'The response target is about to be missed.',
      evidence: [
        overdue ? `Target passed ${hours}h ago` : `Target in ${hours}h`,
        `Priority ${ticket.priority}`,
      ],
      record: { type: 'ticket', id: ticket.id, label: ticket.ticketNumber },
      action: { type: 'open_ticket', label: 'Open ticket' },
    }));
  }

  // ── Deals ────────────────────────────────────────────────────────────────
  for (const deal of openDeals) {
    const health = scoreDealHealth(buildHealthSignals(deal, {
      lastActivityAt: lastActivity.get(deal.id) ?? deal.stageHistory.at(-1)?.changedAt ?? null,
      openTaskCount: openTasks.get(deal.id) ?? 0,
      now,
    }));

    const label = `${deal.title}${deal.contact?.name ? ` (${deal.contact.name})` : ''}`;
    const base = { record: { type: 'deal', id: deal.id, label: deal.title } };

    for (const risk of health.risks) {
      if (risk.key === 'closeDateExpired') {
        out.push(rec({
          ...base,
          key: `deal:${deal.id}:close`,
          urgency: URGENCY.CLOSE_DATE_PASSED,
          title: `Update the close date on ${label}`,
          why: 'The expected close date has passed, so this deal is distorting the forecast.',
          evidence: [risk.message],
          action: { type: 'open_deal', label: 'Review deal' },
        }));
      } else if (risk.key === 'noActivity') {
        out.push(rec({
          ...base,
          key: `deal:${deal.id}:silent`,
          urgency: URGENCY.DEAL_NO_ACTIVITY,
          title: `Reach out on ${label}`,
          why: 'Nothing has been logged against this deal recently.',
          evidence: [risk.message, `Currently in ${deal.stage.replace(/_/g, ' ').toLowerCase()}`],
          action: { type: 'open_deal', label: 'Open deal' },
        }));
      } else if (risk.key === 'stalled') {
        out.push(rec({
          ...base,
          key: `deal:${deal.id}:stalled`,
          urgency: URGENCY.DEAL_STALLED,
          title: `Move ${label} forward or close it out`,
          why: 'It has sat in the same stage far longer than usual.',
          evidence: [risk.message],
          action: { type: 'open_deal', label: 'Open deal' },
        }));
      } else if (risk.key === 'noNextStep') {
        out.push(rec({
          ...base,
          key: `deal:${deal.id}:nextstep`,
          urgency: URGENCY.DEAL_NO_NEXT_STEP,
          title: `Agree a next step on ${label}`,
          why: 'There is no open task, so nothing is scheduled to happen next.',
          evidence: [risk.message],
          action: { type: 'create_task', label: 'Add a task' },
        }));
      } else if (risk.key === 'noValue') {
        out.push(rec({
          ...base,
          key: `deal:${deal.id}:amount`,
          urgency: URGENCY.DEAL_MISSING_AMOUNT,
          title: `Add an amount to ${label}`,
          why: 'Without a value this deal contributes nothing to the pipeline or forecast.',
          evidence: [risk.message],
          action: { type: 'open_deal', label: 'Open deal' },
        }));
      }
    }
  }

  // ── Leads ────────────────────────────────────────────────────────────────
  for (const lead of leads) {
    const age = daysSince(lead.createdAt, now);
    const name = lead.contact?.name || 'this lead';

    // A high score that nobody has acted on is the most expensive thing on
    // this list: the interest is real and going cold.
    if (lead.score >= 60 && lead.status === 'NEW' && age >= 1) {
      out.push(rec({
        key: `lead:${lead.id}:hot`,
        urgency: URGENCY.HOT_LEAD_UNTOUCHED + Math.min(age, 15),
        title: `Follow up with ${name}`,
        why: 'A high-scoring lead has been sitting untouched.',
        evidence: [`Score ${lead.score}/100`, `Created ${age} day${age === 1 ? '' : 's'} ago`, 'Still marked New'],
        record: { type: 'lead', id: lead.id, label: name },
        action: { type: 'open_lead', label: 'Open lead' },
      }));
    }

    if (!lead.ownerUserId && lead.score >= 40) {
      out.push(rec({
        key: `lead:${lead.id}:unowned`,
        urgency: URGENCY.LEAD_UNASSIGNED,
        title: `Assign an owner to ${name}`,
        why: 'Nobody owns this lead, so nobody is accountable for following it up.',
        evidence: [`Score ${lead.score}/100`, 'No owner set'],
        record: { type: 'lead', id: lead.id, label: name },
        action: { type: 'open_lead', label: 'Assign owner' },
      }));
    }
  }

  out.sort((a, b) => b.urgency - a.urgency);
  return { data: out.slice(0, limit), total: out.length };
}
