import 'dotenv/config';
import { z } from 'zod';

const envSchema = z.object({
  PORT: z.coerce.number().default(4000),
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
  CLIENT_URL: z.string().url().default('http://localhost:5173'),
  // Extra allowed CORS origins (comma-separated), e.g. a preview deployment.
  CORS_EXTRA_ORIGINS: z.string().optional(),
  JSON_BODY_LIMIT: z.string().default('2mb'),

  DATABASE_URL: z.string().min(1),
  // Direct (non-pooled) connection for Prisma migrations. Falls back to
  // DATABASE_URL so local setups keep working without extra config.
  DIRECT_URL: z.string().optional(),
  REDIS_URL: z.string().min(1).default('redis://localhost:6379'),

  JWT_ACCESS_SECRET: z.string().min(32),
  JWT_REFRESH_SECRET: z.string().min(32),
  JWT_EXPIRES_IN: z.string().default('15m'),
  JWT_REFRESH_EXPIRES_IN: z.string().default('7d'),

  ADMIN_EMAIL: z.string().email(),
  BCRYPT_SALT_ROUNDS: z.coerce.number().default(12),

  // 32 ASCII chars or 64 hex chars — validated in lib/encryption.js
  ENCRYPTION_KEY: z.string().min(32),

  META_APP_ID: z.string().min(1),
  META_APP_SECRET: z.string().min(1),
  META_BUSINESS_ID: z.string().min(1),
  META_WABA_ID: z.string().min(1),
  META_SYSTEM_USER_ID: z.string().min(1),
  META_SYSTEM_USER_TOKEN: z.string().min(1),
  META_DISPLAY_NAME: z.string().min(1),
  META_WEBHOOK_VERIFY_TOKEN: z.string().min(1),
  META_API_VERSION: z.string().default('v21.0'),
  // Must exactly match the redirect_uri configured in the Meta App dashboard
  // for Embedded Signup. Defaults to the backend callback route.
  META_REDIRECT_URI: z.string().url().optional(),
  // Meta Embedded Signup "configuration ID", created in the App Dashboard
  // under WhatsApp > Embedded Signup. Without this, the frontend can't use
  // FB.login's Embedded Signup flow and silently falls back to the legacy
  // dialog/oauth flow, which throws Meta's "App not active" error for
  // Development-mode apps requesting advanced WhatsApp permissions.
  META_ES_CONFIG_ID: z.string().optional(),

  TWILIO_ACCOUNT_SID: z.string().optional(),
  TWILIO_AUTH_TOKEN: z.string().optional(),

  // Public origin of THIS backend. Twilio signs its webhooks over the exact URL
  // it called, and the Instagram OAuth redirect_uri must match byte-for-byte,
  // so neither can be derived from CLIENT_URL when the two are deployed apart.
  // Defaults to APP_URL (the existing backend-base convention, see below) so no
  // new configuration is needed for the single-service Render deploy.
  API_PUBLIC_URL: z.string().url().optional(),

  // Instagram Quickflows. Falls back to the Meta app credentials above when a
  // dedicated IG app isn't used; the feature stays off until one is present.
  INSTAGRAM_APP_ID: z.string().optional(),
  INSTAGRAM_APP_SECRET: z.string().optional(),
  INSTAGRAM_REDIRECT_URI: z.string().url().optional(),

  // BullMQ idle-polling tuning. Every blocking poll and stalled-job check is a
  // billed request on a hosted Redis (Upstash), and three workers poll around
  // the clock whether or not any job exists — the defaults below are ~10x
  // cheaper than BullMQ's (5s / 30s) while costing nothing in pickup latency:
  // a waiting worker is still woken immediately when a job is pushed.
  WORKER_DRAIN_DELAY_SEC: z.coerce.number().default(60),
  // Trade-off: this is how long a job orphaned by a crashed worker waits before
  // another worker reclaims it. Lower it if faster recovery matters more than
  // request volume.
  WORKER_STALLED_INTERVAL_MS: z.coerce.number().default(300_000),

  CAMPAIGN_BATCH_SIZE: z.coerce.number().default(50),
  CAMPAIGN_WORKER_CONCURRENCY: z.coerce.number().default(2),
  // Meta Cloud API Tier-1 numbers allow ~250 msgs/min → 1 msg / 250ms is safe.
  CAMPAIGN_RATE_DELAY_MS: z.coerce.number().default(250),

  GOOGLE_CLIENT_ID: z.string().min(1),
  GOOGLE_CLIENT_SECRET: z.string().min(1),
  GOOGLE_CALLBACK_URL: z.string().url().optional(),
  GEMINI_API_KEY: z.string().optional(),
  // Pinned model ids get retired — `gemini-2.5-flash` started rejecting new
  // API keys with a 404 ("no longer available to new users"), which silently
  // broke every AI feature. The `-latest` alias tracks the current Flash model
  // instead; override this only to pin a specific version deliberately.
  GEMINI_MODEL: z.string().default('gemini-flash-latest'),
  // Image generation is a separate family of models and, unlike text, is not
  // offered on the Gemini free tier at all — a free key reports
  // "limit: 0" for it, so header generation needs billing enabled on the key.
  GEMINI_IMAGE_MODEL: z.string().default('gemini-2.5-flash-image'),
  // Header images are generated by OpenAI when this is set, because Gemini's
  // image models are not on its free tier at all (see above). Gemini remains
  // the fallback, so removing this key restores the previous behaviour.
  OPENAI_API_KEY: z.string().optional(),
  // `gpt-image-1` requires a verified OpenAI organisation. If verification is
  // the blocker, `dall-e-3` needs no verification and is handled here too.
  OPENAI_IMAGE_MODEL: z.string().default('gpt-image-1'),
  // 'low' | 'medium' | 'high' on gpt-image-1; 'standard' | 'hd' on dall-e-3.
  // Medium is the cost/quality balance that suits a small WhatsApp header.
  OPENAI_IMAGE_QUALITY: z.string().default('medium'),
  OLLAMA_URL: z.string().url().default('http://127.0.0.1:11434'),
  OLLAMA_MODEL: z.string().default('phi3'),

  // Razorpay test/live keys — optional until subscription checkout is configured.
  RAZORPAY_KEY_ID: z.string().optional(),
  RAZORPAY_KEY_SECRET: z.string().optional(),

  // SMTP — optional until credentials are configured
  SMTP_HOST: z.string().optional(),
  SMTP_PORT: z.coerce.number().default(587),
  SMTP_SECURE: z.string().default('false').transform((v) => v === 'true'),
  SMTP_USER: z.string().optional(),
  SMTP_PASSWORD: z.string().optional(),
  EMAIL_FROM_NAME: z.string().default('ChatFlow Pro'),
  EMAIL_FROM: z.string().optional(),
  APP_URL: z.string().url().optional(),
});

const parsed = envSchema.safeParse(process.env);

if (!parsed.success) {
  console.error('Invalid environment variables:');
  console.error(parsed.error.flatten().fieldErrors);
  process.exit(1);
}

const base = parsed.data;

// Prisma reads DIRECT_URL from process.env directly — provide the fallback there too.
if (!process.env.DIRECT_URL) process.env.DIRECT_URL = base.DATABASE_URL;

const backendBase = base.APP_URL ?? `http://localhost:${base.PORT}`;

export const env = {
  ...base,
  DIRECT_URL: base.DIRECT_URL ?? base.DATABASE_URL,
  GOOGLE_CALLBACK_URL:
    base.GOOGLE_CALLBACK_URL ?? `${backendBase}/api/v1/auth/google/callback`,
  META_REDIRECT_URI:
    base.META_REDIRECT_URI ?? `${backendBase}/api/v1/auth/meta/callback`,
  // Twilio validates its signature against the exact URL it called, and the
  // Instagram redirect_uri must match the app config byte-for-byte — both
  // resolve off the same backend base as the OAuth callbacks above.
  API_PUBLIC_URL: base.API_PUBLIC_URL ?? backendBase,
  INSTAGRAM_REDIRECT_URI:
    base.INSTAGRAM_REDIRECT_URI ?? `${backendBase}/api/v1/auth/instagram/callback`,
  CORS_ORIGINS: [
    base.CLIENT_URL,
    ...(base.CORS_EXTRA_ORIGINS ? base.CORS_EXTRA_ORIGINS.split(',').map((s) => s.trim()).filter(Boolean) : []),
  ],
};
